# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=70)),
                ('site_link', models.CharField(max_length=200)),
            ],
        ),
    ]
