# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('positions', models.TextField()),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('position', models.TextField()),
            ],
        ),
    ]
